

#' Generate a dataset for validating methodology
#'
#' Generate a validation dataset with `n` observations in each of `K` groups. Variables include one outcome (Y), one exposure (X), one mediator (M) and two confounders (C1 and C2). All variables are binary. Default values are provided for regression parameters (fixed effects and covariances of random effects).
#'
#' @param n Number of observations in each group.
#' @param K Number of groups
#' @param all_reg_pars A named list containing fixed and mixed effects parameters for both regression models. Best obtained from `make_all_reg_pars()`.
#' @param output_list Should output be formatted as a list with one component per group (of size n-by-5) or a single tibble of size (Kn)-by-6 with a column labelled `group`?
#'
#' @return A simulated dataset.
#' @export
#'
#' @examples
#' n = 20
#' K = 3
#' all_reg_pars = make_all_reg_pars()
#'
#' # Format output as a list
#' make_validation_data(n, K, all_reg_pars, output_list = TRUE)
#'
#' # Format output as a tibble
#' make_validation_data(n, K, all_reg_pars, output_list = FALSE)
make_validation_data <- function(n, K, all_reg_pars = NULL, output_list = TRUE){
  if(is.null(all_reg_pars)) all_reg_pars = make_all_reg_pars()

  # Generate data as a list
  data_list = make_validation_data_list(n, K, all_reg_pars)

  # Optionally, stack groups into a single tibble
  if(!output_list){
    data_tibble = list_2_tibble(data_list)
    return(data_tibble)
  } else{
    return(data_list)
  }
}



#' Store all regression parameters in a single list
#'
#' @param beta_Y Vector of length 4 containing fixed-effects for the outcome model. Order of variables is: Intercept, X, M, C.
#' @param Gamma_Y Covariance matrix of size 3x3 containing random effects for the outcome model. Order of variables is: Intercept, X, M.
#' @param beta_M Vector of length 3 containing fixed-effects for the outcome model. Order is: Intercept, X, C.
#' @param Gamma_M Covariance matrix of size 2x2 containing random effects for the outcome model. Order of variables is: Intercept, X.
#'
#' @return A named list containing fixed and random effects parameters for both the outcome and mediator regression models. Names in list match names of arguments to this function.
#' @export
#'
#' @examples
#' make_all_reg_pars()
make_all_reg_pars <- function(beta_Y = rep(1, times=4), Gamma_Y = matrix(rep(1, times=9), nrow = 3), beta_M = rep(1, times = 3), Gamma_M = matrix(rep(1, times=4), nrow = 2)){
  list(beta_Y = beta_Y, Gamma_Y = Gamma_Y, beta_M = beta_M, Gamma_M = Gamma_M)
}





#' Generate non-random covariates for validation dataset (i.e. intercept, X and C)
#'
#' @param K Number of groups
#' @param N Number of observations per group
#'
#' @return A list of tibbles. One entry for each group, containing all observations for that group.
#' @export
#'
#' @examples
#' K=2
#' N=10
#' build_valid_deterministic_covs(K, N)
build_valid_deterministic_covs <- function(K, N){
  preds_by_K = lapply(1:K, function(x){
    this_Xs = stats::rbinom(N, 1, 0.5)
    this_Cs = stats::rbinom(N, 1, 0.5)

    this_data = tibble::tibble(X = this_Xs, C = this_Cs)
    return(this_data)
  })
}


#' Construct an n-by-p matrix with standard normal elements
#'
#' @param n Number of rows.
#' @param p Number of columns.
#'
#' @return An n-by-p matrix.
#' @export
#'
#' @examples
#' n=20
#' p=3
#' make_some_data(n, p)
make_some_data <- function(n, p){
  matrix(stats::rnorm(n*p), nrow = n, ncol = p)
}



#' Construct a full dataset with K groups, each containing fixed and random effects design matrices
#'
#' @param K Number of groups.
#' @param n Number of observations per group.
#' @param p Number of covariates with fixed effects.
#' @param q Number of covariates with random effects.
#'
#' @return A list of length K. Each element is a list of length 2. The first element is an n-by-p matrix of fixed effects covariates. The second element is an n-by-q matrix of random effects covariates. Both matrices are generated by `make_some_data()`.
#' @export
#'
#' @examples
#' K=3
#' n=20
#' p=3
#' q=2
#'
#' data_by_K = make_dataset(K, n, p, q)
make_dataset <- function(K, n, p, q){
  replicate(K, {
    X = make_some_data(n, p)
    Z = make_some_data(n, q)
    return(list(X=X, Z=Z))
  }, simplify=FALSE)
}



data_by_K = make_dataset(3, 20, 3, 2)
beta = c(1,2,3)
u_by_K = list(c(1,1), c(2,2), c(3,3))


#' Compute the linear predictors in each group
#'
#' @param data_by_K A list of length K, where each element is a list with first component the fixed effects design matrix and second component the random effects design matrix.
#' @param beta A vector of fixed effects.
#' @param u_by_K A list of length K, where each element is a vector of random effects for group k.
#'
#' @return A list of length K. Each element is a vector of length `n` containing the linear predictor for each observation in group `k`.
#' @export
#'
#' @examples
#' K=3
#' n=20
#' p=3
#' q=2
#'
#' data_by_K = make_dataset(K, n, p, q)
#' beta = c(1,2,3)
#' u_by_K = list(c(1,1), c(2,2), c(3,3))
#' get_lin_preds(data_by_K, beta, u_by_K)
get_lin_preds <- function(data_by_K, beta, u_by_K){
  K = length(data_by_K)

  X_by_K = get_index_list(data_by_K, 1)
  Z_by_K = get_index_list(data_by_K, 2)

  fixed_contrib_by_K = purrr::map(X_by_K, function(X) X %*% beta)
  random_contrib_by_K = purrr::map2(Z_by_K, u_by_K, \(x, y) x %*% y)

  total_contrib_by_K = purrr::map2(fixed_contrib_by_K, random_contrib_by_K, `+`)
  return(total_contrib_by_K)

}
