

#' Generate non-random covariates for validation dataset (i.e. intercept, X and C)
#'
#' @param K Number of groups
#' @param N Number of observations per group
#'
#' @return A list of tibbles. One entry for each group, containing all observations for that group.
#' @export
#'
#' @examples
#' K=2
#' N=10
#' build_valid_deterministic_covs(K, N)
build_valid_deterministic_covs <- function(K, N){
  preds_by_K = lapply(1:K, function(x){
    this_Xs = stats::rbinom(N, 1, 0.5)
    this_Cs = stats::rbinom(N, 1, 0.5)

    this_data = tibble::tibble(X = this_Xs, C = this_Cs)
    return(this_data)
  })
}


#' Construct an n-by-p matrix with standard normal elements
#'
#' @param n Number of rows.
#' @param p Number of columns.
#'
#' @return An n-by-p matrix.
#' @export
#'
#' @examples
#' n=20
#' p=3
#' make_some_data(n, p)
make_some_data <- function(n, p){
  matrix(stats::rnorm(n*p), nrow = n, ncol = p)
}



#' Construct a full dataset with K groups, each containing fixed and random effects design matrices
#'
#' @param K Number of groups.
#' @param n Number of observations per group.
#' @param p Number of covariates with fixed effects.
#' @param q Number of covariates with random effects.
#'
#' @return A list of length K. Each element is a list of length 2. The first element is an n-by-p matrix of fixed effects covariates. The second element is an n-by-q matrix of random effects covariates. Both matrices are generated by `make_some_data()`.
#' @export
#'
#' @examples
#' K=3
#' n=20
#' p=3
#' q=2
#'
#' data_by_K = make_dataset(K, n, p, q)
make_dataset <- function(K, n, p, q){
  replicate(K, {
    X = make_some_data(n, p)
    Z = make_some_data(n, q)
    return(list(X=X, Z=Z))
  }, simplify=FALSE)
}



data_by_K = make_dataset(3, 20, 3, 2)
beta = c(1,2,3)
u_by_K = list(c(1,1), c(2,2), c(3,3))


#' Compute the linear predictors in each group
#'
#' @param data_by_K A list of length K, where each element is a list with first component the fixed effects design matrix and second component the random effects design matrix.
#' @param beta A vector of fixed effects.
#' @param u_by_K A list of length K, where each element is a vector of random effects for group k.
#'
#' @return A list of length K. Each element is a vector of length `n` containing the linear predictor for each observation in group `k`.
#' @export
#'
#' @examples
#' K=3
#' n=20
#' p=3
#' q=2
#'
#' data_by_K = make_dataset(K, n, p, q)
#' beta = c(1,2,3)
#' u_by_K = list(c(1,1), c(2,2), c(3,3))
#' get_lin_preds(data_by_K, beta, u_by_K)
get_lin_preds <- function(data_by_K, beta, u_by_K){
  K = length(data_by_K)

  X_by_K = get_index_list(data_by_K, 1)
  Z_by_K = get_index_list(data_by_K, 2)

  fixed_contrib_by_K = purrr::map(X_by_K, function(X) X %*% beta)
  random_contrib_by_K = purrr::map2(Z_by_K, u_by_K, \(x, y) x %*% y)

  total_contrib_by_K = purrr::map2(fixed_contrib_by_K, random_contrib_by_K, `+`)
  return(total_contrib_by_K)

}
