


#' Construct a non-parametric bootstrap sample from the provided data, conditional on group structure
#'
#' @param data A data frame. Must contain a variable called `group`.
#'
#' @return A new data frame generated by subsampling independently within each group.
#' @export
#'
#' @examples
#' n = 20
#' K = 3
#' all_reg_pars = make_all_reg_pars()
#' data = make_validation_data(n, K, all_reg_pars)
#'
#' one_non_parametric_sample(data)
one_non_parametric_sample <- function(data){
  new_data = data %>% dplyr::group_by(group) %>%      # Split data into groups
    dplyr::slice_sample(prop = 1, replace = TRUE) %>% # Resample within each group
    dplyr::ungroup()                                  # Remove grouping structure
  return(new_data)
}
